// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7HGzCLE7CQCSKH8i3HkaHmhCLAXHSwY',
    appId: '1:203983592103:web:4127702c5482379b849982',
    messagingSenderId: '203983592103',
    projectId: 'chattranz',
    authDomain: 'chattranz.firebaseapp.com',
    storageBucket: 'chattranz.appspot.com',
    measurementId: 'G-K6RV6DD04B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGMs1V8X5Ezf3Ewa_SyIaIkyLoLv-_Q0U',
    appId: '1:203983592103:android:6d71a22d964fa887849982',
    messagingSenderId: '203983592103',
    projectId: 'chattranz',
    storageBucket: 'chattranz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBj6jNOyCOpRCY1lBKDuDQrFFu1BdtoYg',
    appId: '1:203983592103:ios:174d5c846f3d1b40849982',
    messagingSenderId: '203983592103',
    projectId: 'chattranz',
    storageBucket: 'chattranz.appspot.com',
    iosBundleId: 'com.example.chattranz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBj6jNOyCOpRCY1lBKDuDQrFFu1BdtoYg',
    appId: '1:203983592103:ios:174d5c846f3d1b40849982',
    messagingSenderId: '203983592103',
    projectId: 'chattranz',
    storageBucket: 'chattranz.appspot.com',
    iosBundleId: 'com.example.chattranz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx7HGzCLE7CQCSKH8i3HkaHmhCLAXHSwY',
    appId: '1:203983592103:web:cdccffab9d1626ce849982',
    messagingSenderId: '203983592103',
    projectId: 'chattranz',
    authDomain: 'chattranz.firebaseapp.com',
    storageBucket: 'chattranz.appspot.com',
    measurementId: 'G-P9PFJZ3RPE',
  );
}
